language: node_js
node_js: stable

install:
  - npm install
  - npm audit fix
  - cd themes/obsidian
  - npm install
  - cd ../..
  
script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Alpha Hinex"
  - git config user.email "AlphaHinex@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force "https://$GH_TOKEN@$GH_REF" master:master

branches:
  only:
    - develop
env:
 global:
   - GH_REF: github.com/AlphaHinex/AlphaHinex.github.io
